package blueprint

type FirstbootCustomization struct {
	// Firstboot scripts to be executed on the first boot of the system.
	// The order of the scripts is important, they will be executed in the
	// order they are defined in the blueprint.
	Custom []CustomFirstbootCustomization `json:"custom,omitempty" toml:"custom,omitempty"`

	// Optional Satellite firstboot customization which is executed before all
	// custom firstboot scripts.
	Satellite *SatelliteFirstbootCustomization `json:"satellite,omitempty" toml:"satellite,omitempty"`

	// Optional Ansible Automation Platform (AAP) firstboot customization which
	// is executed before all custom firstboot scripts.
	AAP *AAPFirstbootCustomization `json:"aap,omitempty" toml:"aap,omitempty"`
}

type CustomFirstbootCustomization struct {
	// Required firstboot script contents. Strings without shebang will be
	// interpreted as shell scripts, otherwise the script will be executed
	// using the shebang interpreter.
	Contents string `json:"contents,omitempty" toml:"contents,omitempty"`

	// Optional firstboot name. Must be unique within the blueprint and only
	// alphanumeric characters with dashes and underscores are allowed.
	Name string `json:"name,omitempty" toml:"name,omitempty"`

	// Ignore errors when executing the firstboot script and continue with
	// execution of the following firstboot scripts, if any. By default,
	// firstboot scripts are executed in order and if one of them fails, the
	// execution stops immediately.
	IgnoreFailure bool `json:"ignore_failure,omitempty" toml:"ignore_failure,omitempty"`
}

type SatelliteFirstbootCustomization struct {
	// Registration command as generated by the Satellite server.
	Command string `json:"command,omitempty" toml:"command,omitempty"`

	// Optional CA certificate for the registration command.
	CACerts []string `json:"cacerts,omitempty" toml:"cacerts,omitempty"`
}

type AAPFirstbootCustomization struct {
	// Job template URL as generated by the AAP server. Required. Example:
	// https://aap.example.com/api/controller/v2/job_templates/9/callback/ or
	// https://aap.example.com/api/v2/job_templates/9/callback/ depending on the AAP version.
	JobTemplateURL string `json:"job_template_url,omitempty" toml:"job_template_url,omitempty"`

	// Required host config key.
	HostConfigKey string `json:"host_config_key,omitempty" toml:"host_config_key,omitempty"`

	// Optional CA certificate for the registration command.
	CACerts []string `json:"cacerts,omitempty" toml:"cacerts,omitempty"`
}
