---
stages:
  - init
  - gen
  - build
  - ostree-gen
  - ostree-build
  - verify
  - finish

variables:
  # Set the parent pipeline ID as a global variable so that the child pipeline
  # jobs can use it to retrieve artifacts.
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

check-build-coverage:
  stage: verify
  extends: .terraform
  variables:
    RUNNER: aws/fedora-40-x86_64
    INTERNAL_NETWORK: "true"
    PYTHONUNBUFFERED: 1
  script:
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/check-build-coverage ./s3configs/
  cache:
    key: testcache
    paths:
      - .cache/osbuild-images

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish

fail:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh fail
    - exit 1  # make the pipeline fail so it doesn't look like success
  when: on_failure

.base:
  before_script:
    - cat schutzbot/team_ssh_keys.txt |
        tee -a ~/.ssh/authorized_keys > /dev/null
  interruptible: true
  retry: 1
  tags:
    - terraform
  variables:
    PYTHONUNBUFFERED: 1

.terraform:
  extends: .base
  tags:
    - terraform

generate-build-config-rhel-9.4-aarch64:
  stage: gen
  extends: .terraform
  variables:
    RUNNER: aws/fedora-40-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/generate-build-config --distro rhel-9.4 --arch aarch64 build-config.yml
  artifacts:
    paths:
      - build-config.yml
  cache:
    key: testcache
    paths:
      - .cache/osbuild-images


generate-build-config-rhel-9.4-x86_64:
  stage: gen
  extends: .terraform
  variables:
    RUNNER: aws/fedora-40-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/generate-build-config --distro rhel-9.4 --arch x86_64 build-config.yml
  artifacts:
    paths:
      - build-config.yml
  cache:
    key: testcache
    paths:
      - .cache/osbuild-images

image-build-trigger-rhel-9.4-aarch64:
  stage: build
  trigger:
    include:
      - artifact: build-config.yml
        job: generate-build-config-rhel-9.4-aarch64
    strategy: depend
  needs:
    - generate-build-config-rhel-9.4-aarch64


image-build-trigger-rhel-9.4-x86_64:
  stage: build
  trigger:
    include:
      - artifact: build-config.yml
        job: generate-build-config-rhel-9.4-x86_64
    strategy: depend
  needs:
    - generate-build-config-rhel-9.4-x86_64

generate-ostree-build-config-rhel-9.4-aarch64:
  stage: ostree-gen
  extends: .terraform
  variables:
    RUNNER: aws/fedora-40-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/generate-ostree-build-config --distro rhel-9.4 --arch aarch64 build-config.yml build-configs
  artifacts:
    paths:
      - build-config.yml
      - build-configs
  needs:
    - image-build-trigger-rhel-9.4-aarch64
  cache:
    key: testcache
    paths:
      - .cache/osbuild-images


generate-ostree-build-config-rhel-9.4-x86_64:
  stage: ostree-gen
  extends: .terraform
  variables:
    RUNNER: aws/fedora-40-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/generate-ostree-build-config --distro rhel-9.4 --arch x86_64 build-config.yml build-configs
  artifacts:
    paths:
      - build-config.yml
      - build-configs
  needs:
    - image-build-trigger-rhel-9.4-x86_64
  cache:
    key: testcache
    paths:
      - .cache/osbuild-images

image-build-ostree-trigger-rhel-9.4-aarch64:
  stage: ostree-build
  trigger:
    include:
      - artifact: build-config.yml
        job: generate-ostree-build-config-rhel-9.4-aarch64
    strategy: depend
  needs:
    - generate-ostree-build-config-rhel-9.4-aarch64


image-build-ostree-trigger-rhel-9.4-x86_64:
  stage: ostree-build
  trigger:
    include:
      - artifact: build-config.yml
        job: generate-ostree-build-config-rhel-9.4-x86_64
    strategy: depend
  needs:
    - generate-ostree-build-config-rhel-9.4-x86_64

generate-manifests-rhel-9.4-ppc64le:
  stage: gen
  extends: .terraform
  variables:
    RUNNER: aws/fedora-40-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.4 --workers 10 --metadata=false --output ./manifests
    - for manifest in ./manifests/*; do
        if osbuild --inspect $manifest > output; then
          echo "$manifest OK";
        else
          cat output;
        fi;
      done


generate-manifests-rhel-9.4-s390x:
  stage: gen
  extends: .terraform
  variables:
    RUNNER: aws/fedora-40-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - go run ./cmd/gen-manifests --arches s390x --distros rhel-9.4 --workers 10 --metadata=false --output ./manifests
    - for manifest in ./manifests/*; do
        if osbuild --inspect $manifest > output; then
          echo "$manifest OK";
        else
          cat output;
        fi;
      done
