---
stages:
  - init
  - build
  - finish

variables:
  # Set the parent pipeline ID as a global variable so that the child pipeline
  # jobs can use it to retrieve artifacts.
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GOPROXY: "https://proxy.golang.org,direct"

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish

fail:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh fail
    - exit 1  # make the pipeline fail so it doesn't look like success
  when: on_failure

.base:
  before_script:
    - cat schutzbot/team_ssh_keys.txt |
        tee -a ~/.ssh/authorized_keys > /dev/null
  interruptible: true
  retry: 1
  tags:
    - terraform
  variables:
    PYTHONUNBUFFERED: 1

.terraform:
  extends: .base
  tags:
    - terraform

"build-images: [centos-10, aarch64]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-42-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/build-all --distro centos-10 --arch aarch64


"build-images: [centos-10, x86_64]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-42-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/build-all --distro centos-10 --arch x86_64
