---
stages:
  - init
  - gen
  - test
  - verify
  - finish

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

configure-generators:
  stage: gen
  image: fedora:latest
  variables:
    PYTHONUNBUFFERED: 1
  script:
    - dnf install -qy golang python3 gpgme-devel
    - ./test/scripts/configure-generators generator-config.yml
  artifacts:
    paths:
      - generator-config.yml

generator-trigger:
  stage: test
  trigger:
    include:
      - artifact: generator-config.yml
        job: configure-generators
    strategy: depend

check-build-coverage:
  stage: verify
  image: fedora:latest
  variables:
    PYTHONUNBUFFERED: 1
  script:
    - dnf install -qy golang python3 gpgme-devel s3cmd
    - ./test/scripts/check-build-coverage ./s3configs/
  cache:
    key: testcache
    paths:
      - .cache/osbuild-images

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
