---
stages:
  - init
  - gen
  - test
  - verify
  - finish

.base:
  before_script:
    - mkdir -p /tmp/artifacts
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-before-run.txt
    - cat schutzbot/team_ssh_keys.txt |
        tee -a ~/.ssh/authorized_keys > /dev/null
  after_script:
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-after-run.txt || true
    - schutzbot/update_github_status.sh update || true
    - schutzbot/save_journal.sh || true
    - schutzbot/upload_artifacts.sh
  interruptible: true
  retry: 1
  tags:
    - terraform
  artifacts:
    paths:
      - "*.repo"
      - COMPOSER_NVR
    when: always

.terraform:
  extends: .base
  tags:
    - terraform

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

configure-generators:
  stage: gen
  image: alpine:latest
  variables:
    PYTHONUNBUFFERED: 1
  script:
    - apk add -U go python3 gpgme-dev
    - ./test/generators/configure-generators generator-config.yml
  artifacts:
    paths:
      - generator-config.yml

generator-trigger:
  stage: test
  trigger:
    include:
      - artifact: generator-config.yml
        job: configure-generators
    strategy: depend

check-build-coverage:
  stage: verify
  image: alpine:latest
  variables:
    PYTHONUNBUFFERED: 1
  script:
    - apk add -U go python3 gpgme-dev s3cmd
    - ./test/generators/check-build-coverage ./s3configs/

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
