stages:
  - init
  - test
  - finish

.base:
  before_script:
    - mkdir -p /tmp/artifacts
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-before-run.txt
    - cat schutzbot/team_ssh_keys.txt | tee -a ~/.ssh/authorized_keys > /dev/null
  after_script:
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-after-run.txt || true
    - schutzbot/update_github_status.sh update || true
    - schutzbot/save_journal.sh || true
    - schutzbot/upload_artifacts.sh
  interruptible: true
  retry: 1
  tags:
    - terraform
  artifacts:
    paths:
      - "*.repo"
      - COMPOSER_NVR
    when: always

.terraform:
  extends: .base
  tags:
    - terraform

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

Manifest-diff:
  stage: test
  extends: .terraform
  rules:
    # don't run on main
    - if: '$CI_COMMIT_BRANCH != "main"'
  script:
    - ./test/cases/diff-manifests.sh
  variables:
    RUNNER: aws/rhel-9.3-nightly-x86_64
    INTERNAL_NETWORK: "true"
    GIT_STRATEGY: "clone"
    GIT_CHECKOUT: "true"
    GIT_DEPTH: 500
  artifacts:
    paths:
      - manifests.diff

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
