---
stages:
  - init
  - gen
  - test
  - gen-ostree
  - test-ostree
  - finish

variables:
  # Set the parent pipeline ID as a global variable so that the child pipeline
  # jobs can use it to retrieve artifacts.
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID

.base:
  before_script:
    - mkdir -p /tmp/artifacts
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-before-run.txt
    - cat schutzbot/team_ssh_keys.txt |
        tee -a ~/.ssh/authorized_keys > /dev/null
  after_script:
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-after-run.txt || true
    - schutzbot/update_github_status.sh update || true
    - schutzbot/save_journal.sh || true
    - schutzbot/upload_artifacts.sh
  interruptible: true
  retry: 1
  tags:
    - terraform
  artifacts:
    paths:
      - "*.repo"
      - COMPOSER_NVR
    when: always

.terraform:
  extends: .base
  tags:
    - terraform

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

generate-build-config:
  stage: gen
  extends: .terraform
  variables:
    RUNNER: aws/fedora-38-x86_64
    INTERNAL_NETWORK: "true"
    PYTHONUNBUFFERED: 1
  script:
    - sudo dnf -y install go python3 gpgme-devel s3cmd
      osbuild osbuild-luks2 osbuild-lvm2 osbuild-ostree osbuild-selinux
    - ./test/generate-build-config build-config.yml
  artifacts:
    paths:
      - build-config.yml

image-build-trigger:
  stage: test
  trigger:
    include:
      - artifact: build-config.yml
        job: generate-build-config
    strategy: depend

generate-ostree-build-config-x86_64:
  stage: gen-ostree
  extends: .terraform
  variables:
    RUNNER: aws/fedora-38-x86_64
    INTERNAL_NETWORK: "true"
    PYTHONUNBUFFERED: 1
  script:
    - sudo dnf -y install go python3 gpgme-devel s3cmd
      osbuild osbuild-luks2 osbuild-lvm2 osbuild-ostree osbuild-selinux podman
    - ./test/generate-ostree-build-config build-config.yml build-configs
  artifacts:
    paths:
      - build-config.yml
      - build-configs

generate-ostree-build-config-aarch64:
  stage: gen-ostree
  extends: .terraform
  variables:
    RUNNER: aws/fedora-38-aarch64
    INTERNAL_NETWORK: "true"
    PYTHONUNBUFFERED: 1
  script:
    - sudo dnf -y install go python3 gpgme-devel s3cmd
      osbuild osbuild-luks2 osbuild-lvm2 osbuild-ostree osbuild-selinux podman
    - ./test/generate-ostree-build-config build-config.yml build-configs
  artifacts:
    paths:
      - build-config.yml
      - build-configs

image-build-ostree-trigger-x86_64:
  stage: test-ostree
  trigger:
    include:
      - artifact: build-config.yml
        job: generate-ostree-build-config-x86_64
    strategy: depend

image-build-ostree-trigger-aarch64:
  stage: test-ostree
  trigger:
    include:
      - artifact: build-config.yml
        job: generate-ostree-build-config-aarch64
    strategy: depend

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
