version: "2"
run:
  build-tags:
    - integration
linters:
  enable:
    - gosec
  settings:
    gosec:
      excludes:
        - G101
    govet:
      disable:
        - shadow
        - composites
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: ^(images/)?(pkg|internal)/.*_test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
