---
version: "2"
run:
  build-tags:
    - integration

linters:
  enable:
    - gosec
  settings:
    gosec:
      excludes:
        - G101
    govet:
      disable:
        # default value recommended by golangci
        - shadow
        - composites
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: ^(images/)?(pkg|internal)/.*_test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default
  # is 3.
  max-same-issues: 0

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
