package firstboot

import (
	"errors"
	"fmt"

	"github.com/osbuild/blueprint/pkg/blueprint"
)

type FirstbootOptions struct {
	Scripts []FirstbootOption
}

// FirstbootCommonOptions contains common fields for all firstboot options.
type FirstbootCommonOptions struct {
	// Optional firstboot name. Must be unique within the blueprint and only
	// alphanumeric characters with dashes and underscores are allowed.
	Name string

	// Ignore errors when executing the firstboot script and continue with
	// execution of the following firstboot scripts, if any. By default,
	// firstboot scripts are executed in order and if one of them fails, the
	// execution stops immediately.
	IgnoreFailure bool
}

// CustomFirstbootOptions contains fields specific to custom firstboot
// options.
type CustomFirstbootOptions struct {
	FirstbootCommonOptions

	// Strings without shebang will be interpreted as shell scripts, otherwise
	// the script will be executed using the shebang interpreter. Required if
	// type is set to "custom".
	Contents string
}

// SatelliteFirstbootOptions contains fields specific to satellite firstboot
// options.
type SatelliteFirstbootOptions struct {
	FirstbootCommonOptions

	// Optional CA certificate to enroll into the system before executing the
	// firstboot script.
	CACerts []string

	// Registration command as generated by the Satellite server. Required, if
	// type is set to "satellite".
	Command string
}

// AAPFirstbootOptions contains fields specific to AAP firstboot options.
type AAPFirstbootOptions struct {
	FirstbootCommonOptions

	// Optional CA certificate to enroll into the system before executing the
	// firstboot script.
	CACerts []string

	// Job template URL as generated by the AAP server. Required if type is set
	// to "aap". Example URLs are
	// https://aap.example.com/api/controller/v2/job_templates/9/callback/ or
	// https://aap.example.com/api/v2/job_templates/9/callback/ depending on the
	// AAP version.
	JobTemplateURL string

	// The host config key. Required if type is set to "aap".
	HostConfigKey string
}

// FirstbootOption is a union of all supported firstboot options.
type FirstbootOption interface {
	isFirstbootOption()
}

func (CustomFirstbootOptions) isFirstbootOption()    {}
func (SatelliteFirstbootOptions) isFirstbootOption() {}
func (AAPFirstbootOptions) isFirstbootOption()       {}

var ErrFirstbootAlreadySet = errors.New("firstboot customization already set")

// FirstbootOptionsFromBP converts a blueprint FirstbootCustomization to
// FirstbootOptions. Validation is done in the blueprint package, so this function
// assumes the input is valid, however, JSON unmarshalling errors are possible.
func FirstbootOptionsFromBP(bpFirstboot blueprint.FirstbootCustomization) (*FirstbootOptions, error) {
	fo := &FirstbootOptions{}
	var satDone, aapDone bool

	for _, fbsc := range bpFirstboot.Scripts {
		cust, sat, aap, err := fbsc.SelectUnion()
		if err != nil {
			return nil, err
		}

		if cust != nil {
			opts := CustomFirstbootOptions{
				FirstbootCommonOptions: FirstbootCommonOptions{
					Name:          cust.Name,
					IgnoreFailure: cust.IgnoreFailure,
				},
				Contents: cust.Contents,
			}
			fo.Scripts = append(fo.Scripts, opts)
		}

		if sat != nil {
			opts := SatelliteFirstbootOptions{
				FirstbootCommonOptions: FirstbootCommonOptions{
					Name:          sat.Name,
					IgnoreFailure: sat.IgnoreFailure,
				},
				CACerts: sat.CACerts,
				Command: sat.Command,
			}
			if satDone {
				return nil, fmt.Errorf("%w: satellite", ErrFirstbootAlreadySet)
			}
			fo.Scripts = append(fo.Scripts, opts)
			satDone = true
		}

		if aap != nil {
			opts := AAPFirstbootOptions{
				FirstbootCommonOptions: FirstbootCommonOptions{
					Name:          aap.Name,
					IgnoreFailure: aap.IgnoreFailure,
				},
				CACerts:        aap.CACerts,
				JobTemplateURL: aap.JobTemplateURL,
				HostConfigKey:  aap.HostConfigKey,
			}
			if aapDone {
				return nil, fmt.Errorf("%w: aap", ErrFirstbootAlreadySet)
			}
			fo.Scripts = append(fo.Scripts, opts)
			aapDone = true
		}
	}

	return fo, nil
}

func (fo *FirstbootOptions) Each(cbCustom func(CustomFirstbootOptions) error, cbSat func(SatelliteFirstbootOptions) error, cbAAP func(AAPFirstbootOptions) error) error {
	for _, script := range fo.Scripts {
		switch s := script.(type) {
		case CustomFirstbootOptions:
			if err := cbCustom(s); err != nil {
				return err
			}
		case SatelliteFirstbootOptions:
			if err := cbSat(s); err != nil {
				return err
			}
		case AAPFirstbootOptions:
			if err := cbAAP(s); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unknown firstboot option type: %T", script)
		}
	}
	return nil
}
