#!/usr/bin/env python3
import argparse
import asyncio
import contextlib
import json
import os
import pathlib
import uuid
import subprocess
import shlex
import shutil
import textwrap
from tempfile import mkdtemp, TemporaryDirectory

import imgtestlib as testlib

BASE_TEST_SCRIPT = "test/scripts/check-host-config.sh"
WSL_TEST_SCRIPT = "test/scripts/wsl-entrypoint.bat"


def get_aws_config():
    return {
        "key_id": os.environ.get("AWS_ACCESS_KEY_ID"),
        "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY"),
        "bucket": os.environ.get("AWS_BUCKET"),
        "region": os.environ.get("AWS_REGION")
    }


def get_azure_config():
    return {
        "subscription": os.environ.get("AZURE_SUBSCRIPTION"),
        "tenant": os.environ.get("AZURE_TENANT"),
        "client_id": os.environ.get("AZURE_CLIENT_ID"),
        "client_secret": os.environ.get("AZURE_CLIENT_SECRET"),
        "resource_group": os.environ.get("AZURE_RESOURCE_GROUP"),
        "windows_snapshot": os.environ.get("AZURE_WINDOWS_SNAPSHOT"),
        "windows_ssh_privkey": os.environ.get("AZURE_WINDOWS_SSH_PRIVKEY"),
    }


@contextlib.contextmanager
def create_ssh_key(privkey_file = None, key_type = None):
    with TemporaryDirectory() as tmpdir:
        keypath = os.path.join(tmpdir, "testkey")
        ci_priv_key = os.environ.get("CI_PRIV_SSH_KEY_2")
        if privkey_file is not None:
            shutil.copyfile(privkey_file, keypath)
            os.chmod(keypath, 0o600)

            cmd = ["ssh-keygen", "-y", "-f", keypath]
            out, _ = testlib.runcmd(cmd)
            pubkey = out.decode()
            with open(keypath + ".pub", "w", encoding="utf-8") as pubkeyfile:
                pubkeyfile.write(pubkey)
        elif not key_type and ci_priv_key:
            # running in CI: use key from env
            with open(keypath, "w", encoding="utf-8") as keyfile:
                keyfile.write(ci_priv_key + "\n")
            os.chmod(keypath, 0o600)

            # get public key from priv key and write it out
            cmd = ["ssh-keygen", "-y", "-f", keypath]
            out, _ = testlib.runcmd(cmd)
            pubkey = out.decode()
            with open(keypath + ".pub", "w", encoding="utf-8") as pubkeyfile:
                pubkeyfile.write(pubkey)
        elif key_type == "rsa":
            cmd = ["ssh-keygen", "-t", "rsa", "-b", "2048", "-m", "pem", "-N", "", "-f", keypath]
            testlib.runcmd_nc(cmd)
        else:
            # create an ssh key pair with empty password
            cmd = ["ssh-keygen", "-t", "ecdsa", "-b", "256", "-m", "pem", "-N", "", "-f", keypath]
            testlib.runcmd_nc(cmd)

        yield keypath, keypath + ".pub"


@contextlib.contextmanager
def ensure_uncompressed(filepath):
    """
    If the file at the given path is compressed, decompress it and return the new file path.
    """
    base, ext = os.path.splitext(filepath)
    if ext == ".xz":
        print(f"Uncompressing {filepath}")
        # needs to run as root to set perms and ownership on uncompressed file
        testlib.runcmd_nc(["sudo", "unxz", "--verbose", "--keep", filepath])
        yield base
        # cleanup when done so the uncompressed file doesn't get uploaded to the build cache
        os.unlink(base)

    else:
        # we only do xz for now so it must be raw: return as is and hope for the best
        yield filepath


@contextlib.contextmanager
def ensure_qcow2(filepath):
    base, ext = os.path.splitext(filepath)
    if ext != ".qcow2":
        print(f"Converting {filepath} to qcow2")
        filepath_qcow2 = base + ".qcow2"
        testlib.runcmd_nc([
            "qemu-img", "convert",
            "-f", "raw",
            "-O", "qcow2",
            "-o", "preallocation=metadata",
            filepath, filepath_qcow2,
        ])
        yield filepath_qcow2
        os.unlink(filepath_qcow2)
    else:
        yield filepath


def make_cloud_init_iso(ssh_key, extra_files = None) -> pathlib.Path:
    with TemporaryDirectory() as tmpdir:
        user_data = pathlib.Path(tmpdir) / "user-data.yaml"
        user_data_content = textwrap.dedent(f"""\
        #cloud-config
        users:
          - name: root
            ssh_authorized_keys:
              - {ssh_key}
        """)
        user_data.write_text(user_data_content)
        meta_data = pathlib.Path(tmpdir) / "meta-data"
        meta_data.write_text('{"instance-id": "i-1234567890abcdef0"}')
        if extra_files:
            extra_files_tar = pathlib.Path(tmpdir) / "extra-files.tar"
            subprocess.check_call(
                ["tar", "cf", os.fspath(extra_files_tar), *extra_files],
            )
            user_data = pathlib.Path(tmpdir) / "user-data-bundle"
            subprocess.check_call(
                ["write-mime-multipart",
                 "--output", user_data,
                 "user-data.yaml:text/cloud-config",
                 "extra-files.tar:text/x-tarfile",
                 ], cwd=tmpdir,
            )
        # XXX: cleanup
        iso_path = pathlib.Path(mkdtemp(prefix="ci-")) / "cloud-init.iso"
        subprocess.check_call(
            ["cloud-localds", os.fspath(iso_path), user_data.name, meta_data.name],
            cwd=tmpdir,
        )
        return iso_path


def mutate_qemu_image_for_login(filepath, pubkey_path):
    here = pathlib.Path(__file__).parent
    pubkey = pathlib.Path(pubkey_path).read_text(encoding="utf8")
    # pylint: disable=import-outside-toplevel
    import guestfs
    g = guestfs.GuestFS()
    try:
        g.add_drive_opts(filepath, readonly=False)
        g.launch()
        roots = g.inspect_os()
        if not roots:
            raise RuntimeError("No operating system found in the image")
        root_device = roots[0]
        g.mount(root_device, "/")
        # we need the right mount in /root (all-customizations sets it on its own lv),
        # sadly "/" and "/root" both are called "rootlv", but the later is rootlv00
        if any([fs[0] == "/dev/rootvg/rootlv00" for fs in g.list_filesystems()]):
            g.mount("/dev/rootvg/rootlv00", "/root")
        # setfiles needs a setup /usr, on lvm setups we need to mount it
        if any([fs[0] == "/dev/rootvg/usrlv" for fs in g.list_filesystems()]):
            g.mount("/dev/rootvg/usrlv", "/usr")
        # add root ssh key for systems that lack systemd credentials
        ssh_dir = "/root/.ssh"
        g.mkdir_p(ssh_dir)
        g.chmod(0o700, ssh_dir)
        auth_keys_file = f"{ssh_dir}/authorized_keys"
        g.write_append(auth_keys_file, pubkey.encode('utf-8'))
        g.chmod(0o600, auth_keys_file)
        # we need /root/.ssh/authorized_keys to be labeled correctly
        # XXX: slightly hackish this will break if we have more than one match (right now "targeted")
        g.sh("setfiles -F -v /etc/selinux/*/contexts/files/file_contexts /root/.ssh/authorized_keys")
    finally:
        g.close()


def boot_qemu(arch, image_path, config, image_type):
    try:
        from vmtest.vm import QEMU
    except ImportError as e:
        print(textwrap.dedent("""\
        ****
        cannot import vmtest, please run 'pip install .'
        ****
        """))
        raise e

    # XXX: cmd must be a script and all arguments must be files too
    cmd = [BASE_TEST_SCRIPT, config]
    with ensure_uncompressed(image_path) as raw_image_path:
        with create_ssh_key(key_type="rsa") as (privkey_path, pubkey_path):
            ssh_key = pathlib.Path(pubkey_path).read_text().strip()
            # put cmd into iso as well via cloud-init
            cloud_init_iso = make_cloud_init_iso(ssh_key, cmd)
            # image types without cloud init
            if image_type in ["minimal-raw"]:
                print("WARNING: modifiyng the image to include root ssh login")
                mutate_qemu_image_for_login(raw_image_path, pubkey_path)
                # XXX: we include the script via cloud-init, for non-cloud init
                # we should implement "scp" and use that. See
                # https://github.com/osbuild/images/compare/main...mvo5:non-test-thing?expand=1
                cmd = ["bin/true"]
            with QEMU(raw_image_path, arch=arch, cdrom=cloud_init_iso) as vm:
                vm.start(use_ovmf=True)
                # run the script, this assumes that we always have a script
                # and files as arguments
                cmd = "/" + shlex.join(cmd)
                exit_status, _ = vm.run(cmd, user="root", keyfile=privkey_path)
                assert exit_status == 0


def cmd_boot_aws(arch, image_name, privkey, pubkey, image_path, script_cmd):
    # pylint: disable=too-many-arguments,too-many-positional-arguments
    aws_config = get_aws_config()
    cmd = ["go", "run", "./cmd/boot-aws", "run",
           "--access-key-id", aws_config["key_id"],
           "--secret-access-key", aws_config["secret_key"],
           "--region", aws_config["region"],
           "--bucket", aws_config["bucket"],
           "--arch", arch,
           "--ami-name", image_name,
           "--s3-key", f"images/boot/{image_name}",
           "--username", "osbuild",
           "--ssh-privkey", privkey,
           "--ssh-pubkey", pubkey,
           image_path, *script_cmd]
    testlib.runcmd_nc(cmd)


def boot_ami(distro, arch, image_type, image_path, config):
    cmd = [BASE_TEST_SCRIPT, config]
    with ensure_uncompressed(image_path) as raw_image_path:
        with create_ssh_key() as (privkey, pubkey):
            image_name = f"image-boot-test-{distro}-{arch}-{image_type}-" + str(uuid.uuid4())
            cmd_boot_aws(arch, image_name, privkey, pubkey, raw_image_path, cmd)


def boot_container(distro, arch, image_type, image_path, manifest_id):
    """
    Use bootc-image-builder to build an AMI and boot it.
    """
    # push container to registry so we can build it with BIB
    # remove when BIB can pull from containers-storage: https://github.com/osbuild/bootc-image-builder/pull/120
    container_name = f"iot-bootable-container:{distro}-{arch}-{manifest_id}"
    cmd = ["./tools/ci/push-container.sh", image_path, container_name]
    testlib.runcmd_nc(cmd)
    container_ref = f"{testlib.REGISTRY}/{container_name}"

    with TemporaryDirectory() as tmpdir:
        with create_ssh_key() as (privkey_file, pubkey_file):
            with open(pubkey_file, encoding="utf-8") as pubkey_fp:
                pubkey = pubkey_fp.read()

            # write a config to create a user
            config_file = os.path.join(tmpdir, "config.json")
            with open(config_file, "w", encoding="utf-8") as cfg_fp:
                config = {
                    "blueprint": {
                        "customizations": {
                            "user": [
                                {
                                    "name": "osbuild",
                                    "key": pubkey,
                                    "groups": [
                                        "wheel"
                                    ]
                                }
                            ]
                        }
                    }
                }
                json.dump(config, cfg_fp)

            # build an AMI
            cmd = ["sudo", "podman", "run",
                   "--rm", "-it",
                   "--privileged",
                   "--pull=newer",
                   "--security-opt", "label=type:unconfined_t",
                   "-v", f"{tmpdir}:/output",
                   "-v", f"{config_file}:/config.json",
                   testlib.get_bib_ref(),
                   "--type=ami",
                   "--config=/config.json",
                   container_ref]
            testlib.runcmd_nc(cmd)

            # boot it
            image_name = f"image-boot-test-{distro}-{arch}-{image_type}-" + str(uuid.uuid4())

            # Build artifacts are owned by root. Make them world accessible.
            testlib.runcmd(["sudo", "chmod", "a+rwX", "-R", tmpdir])
            raw_image_path = f"{tmpdir}/image/disk.raw"
            cmd_boot_aws(arch, image_name, privkey_file, pubkey_file, raw_image_path, [BASE_TEST_SCRIPT])


def boot_vhd(distro, arch, image_path, config):
    cmd = [BASE_TEST_SCRIPT, config]
    with ensure_uncompressed(image_path) as raw_image_path:
        with create_ssh_key(key_type="rsa") as (privkey, pubkey):
            # a lot of resources have <=64 character naming constraint
            name = f"{distro}-" + str(uuid.uuid4())

            # pylint: disable=too-many-arguments,too-many-positional-arguments
            az_config = get_azure_config()
            cmd = ["go", "run", "./cmd/boot-azure", "run",
                   "--subscription", az_config["subscription"],
                   "--tenant", az_config["tenant"],
                   "--client-id", az_config["client_id"],
                   "--client-secret", az_config["client_secret"],
                   "--resource-group", az_config["resource_group"],
                   "--username", "osbuild",
                   "--ssh-privkey", privkey,
                   "--ssh-pubkey", pubkey,
                   "--vm-name", name,
                   "--arch", arch,
                   "--image-name", name,
                   raw_image_path, *cmd]
            testlib.runcmd_nc(cmd)


def boot_wsl(distro, arch, image_path, config):
    with ensure_uncompressed(image_path) as raw_image_path:
        cmd = [WSL_TEST_SCRIPT, raw_image_path, BASE_TEST_SCRIPT, config]
        # pylint: disable=too-many-arguments,too-many-positional-arguments
        az_config = get_azure_config()
        with create_ssh_key(privkey_file = az_config["windows_ssh_privkey"]) as (privkey, pubkey):
            # a lot of resources have <=64 character naming constraint
            name = f"{distro}-" + str(uuid.uuid4())

            cmd = ["go", "run", "./cmd/boot-azure", "run",
                   "--subscription", az_config["subscription"],
                   "--tenant", az_config["tenant"],
                   "--client-id", az_config["client_id"],
                   "--client-secret", az_config["client_secret"],
                   "--resource-group", az_config["resource_group"],
                   "--snapshot", az_config["windows_snapshot"],
                   "--username", "azureuser",
                   "--ssh-privkey", privkey,
                   "--ssh-pubkey", pubkey,
                   "--vm-name", name,
                   "--arch", arch,
                   "--size", "Standard_D2as_v5",
                   raw_image_path, *cmd]
            testlib.runcmd_nc(cmd)


def main():
    desc = "Boot an image in the cloud environment it is built for and validate the configuration"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("distro", type=str, default=None, help="distro for the image to boot test")
    parser.add_argument("arch", type=str, default=None, help="architecture of the image to boot test")
    parser.add_argument("image_type", type=str, default=None, help="type of the image to boot test")
    parser.add_argument("image_search_path", type=str, help="path to search for image file")

    args = parser.parse_args()
    distro = args.distro
    arch = args.arch
    image_type = args.image_type
    search_path = args.image_search_path

    image_path = testlib.find_image_file(search_path)
    build_info = testlib.read_build_info(search_path)
    build_config_name = build_info["config"]
    build_config_path = f"test/configs/{build_config_name}.json"

    print(f"Testing image at {image_path}")
    bib_image_id = ""
    match image_type:
        case "qcow2" | "minimal-raw":
            boot_qemu(arch, image_path, build_config_path, image_type)
        case "ami" | "ec2" | "ec2-ha" | "ec2-sap" | "edge-ami":
            boot_ami(distro, arch, image_type, image_path, build_config_path)
        case "vhd":
            boot_vhd(distro, arch, image_path, build_config_path)
        case "iot-bootable-container":
            manifest_id = build_info["manifest-checksum"]
            boot_container(distro, arch, image_type, image_path, manifest_id)
            bib_ref = testlib.get_bib_ref()
            bib_image_id = testlib.skopeo_inspect_id(f"docker://{bib_ref}", testlib.host_container_arch())
        case "wsl":
            if distro == "fedora-41":
                print(f"{distro} {image_type} boot tests are not supported, fails on wsl import")
                return
            boot_wsl(distro, arch, image_path, build_config_path)
        case _:
            # skip
            print(f"{image_type} boot tests are not supported yet")
            return

    print("✅ Marking boot successful")
    # amend build info with boot success
    # search_path is the root of the build path (build/build_name)
    build_info["boot-success"] = True
    testlib.write_build_info(search_path, build_info)
    if bib_image_id:
        # write a separate file with the bib image ID as filename to mark the boot success with that image
        bib_id_file = os.path.join(search_path, f"bib-{bib_image_id}")
        print(f"Writing bib image ID file: {bib_id_file}")
        with open(bib_id_file, "w", encoding="utf-8") as fp:
            fp.write("")


if __name__ == "__main__":
    main()
