#!/usr/bin/env python3
import json
import subprocess as sp
import sys


def inspect(filepath):
    with open(filepath) as test_file:
        test_data = json.load(test_file)

    test_manifest = test_data["manifest"]
    job = sp.Popen(["osbuild", "--inspect", "-"], stdin=sp.PIPE, stdout=sp.PIPE)
    out, _ = job.communicate(json.dumps(test_manifest).encode())
    return {
        "code": job.returncode,
        "output": out
    }


def main():
    paths = sys.argv[1:]

    errors = {}
    for filepath in paths:
        print(f"{filepath}", end=" ", flush=True)
        result = inspect(filepath)
        if result["code"] != 0:
            errors[filepath] = result
            print("ERROR")
        else:
            print("OK")

    if errors:
        print(f"\n\nERRORS: {len(errors)} manifests failed to validate")
        for filepath, result in errors.items():
            output = json.dumps(json.loads(result["output"]), indent=2)  # parse and reserialise to format
            print(f"\n\n{filepath}:\n{output}")
        sys.exit(1)


if __name__ == "__main__":
    main()
