#!/usr/bin/env bash

set -e

# we need qemu-kvm here but libvirt-devel pulls this in
dnf -y install \
    awscli2 \
    btrfs-progs-devel \
    cloud-utils \
    device-mapper-devel \
    libvirt-devel \
    gcc \
    go \
    gpgme-devel \
    krb5-devel \
    lorax \
    osbuild \
    osbuild-depsolve-dnf \
    osbuild-luks2 \
    osbuild-lvm2 \
    osbuild-ostree \
    osbuild-selinux \
    podman \
    python3 \
    python3-pip \
    python3-pytest \
    python3-boto3 \
    python3-qemu-qmp \
    python3-scp \
    yamllint \
    xz
