#!/usr/bin/env bash

dnf -y install \
    device-mapper-devel \
    gcc \
    go \
    gpgme-devel \
    osbuild \
    osbuild-depsolve-dnf \
    osbuild-luks2 \
    osbuild-lvm2 \
    osbuild-ostree \
    osbuild-selinux \
    podman \
    python3 \
    xz
