#!/usr/bin/env python3
#
# Add a repository configuration to install the osbuild rpm at a specific
# commit if specified.
import os

import imgtestlib as testlib

REPO_TEMPLATE = """
[osbuild]
name=osbuild {commit}
baseurl=http://osbuild-composer-repos.s3-website.us-east-2.amazonaws.com/{repo_path}
enabled=1
gpgcheck=0
priority=10
"""

REPO_FILE = "/etc/yum.repos.d/osbuild.repo"


def write_repo(commit, distro_version):
    arch = os.uname().machine
    repo_path = f"osbuild/{distro_version}/{arch}/{commit}"
    print(f"Setting up dnf repository for {commit} ({repo_path})")
    with open("/etc/yum.repos.d/osbuild.repo", "w", encoding="utf-8") as repofile:
        repofile.write(REPO_TEMPLATE.format(commit=commit, repo_path=repo_path))


def main():
    osrelease = testlib.read_osrelease()

    distro_version = osrelease["ID"] + "-" + osrelease["VERSION_ID"]
    commit_id = testlib.get_osbuild_commit(distro_version)
    if not commit_id:
        print("No commit ID defined for osbuild")
        return

    write_repo(commit_id, distro_version)


if __name__ == "__main__":
    main()
