---
name: "Updates Go dependencies via gobump"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Every Sunday at 15:00
    - cron: "0 15 * * 0"

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:42
    steps:
      - name: Set up the environment
        run: "sudo dnf -y install git gh golang gpgme-devel btrfs-progs-devel krb5-devel"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gobump-deps action
        uses: lzap/gobump@main
        with:
          token: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
          exec: "go build ./..."
          exec2: "go test ./..."
          labels: "gobump"
          pr: true
          setup_go: false
