---
name: Trigger GitLab CI

on:
  pull_request:
    branches:
      - "*"
  # for merge queue
  merge_group:

jobs:
  gitlab-ci-helper:
    name: "Gitlab CI trigger helper"
    runs-on: ubuntu-latest
    env:
      SKIP_CI: ${{ (github.event.pull_request.draft == true || contains(github.event.pull_request.labels.*.name, 'WIP')) && !contains(github.event.pull_request.labels.*.name, 'WIP+test') }}
    steps:
      - name: Write PR status
        run: echo "$SKIP_CI" > SKIP_CI.txt
      - name: Upload status
        uses: actions/upload-artifact@v3
        with:
          name: PR_STATUS
          path: SKIP_CI.txt

  trigger-gitlab:
    runs-on: ubuntu-latest
    env:
      IMAGEBUILDER_BOT_GITLAB_SSH_KEY: ${{ secrets.IMAGEBUILDER_BOT_GITLAB_SSH_KEY }}
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y jq

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Mark the working directory as safe for git
        run: git config --global --add safe.directory "$(pwd)"

      - uses: octokit/request-action@v2.x
        id: fetch_pulls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/${{ github.repository }}/pulls
          per_page: 100

      - name: Checkout branch
        id: pr_data
        run: |
          PR_DATA=$(mktemp)
          # use uuid as a file terminator to avoid conflicts with data content
          cat > "$PR_DATA" <<'a21b3e7f-d5eb-44a3-8be0-c2412851d2e6'
          ${{ steps.fetch_pulls.outputs.data }}
          a21b3e7f-d5eb-44a3-8be0-c2412851d2e6

          PR=$(jq -rc '.[] | select(.head.sha | contains("${{ github.event.pull_request.head.sha }}")) | select(.state | contains("open"))' "$PR_DATA" | jq -r .number)
          if [ ! -z "$PR" ]; then
            echo "pr_branch=PR-$PR" >> "$GITHUB_OUTPUT"
            git checkout -b PR-$PR
          else
            git checkout ${{ github.event.pull_request.head.ref }}
          fi

      - name: Download PR_STATUS artifact
        uses: actions/download-artifact@v3
        with:
          name: PR_STATUS

      - name: Push to gitlab
        run: |
          mkdir -p ~/.ssh
          echo "${IMAGEBUILDER_BOT_GITLAB_SSH_KEY}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
          git remote add ci git@gitlab.com:redhat/services/products/image-builder/ci/images.git
          SKIP_CI=$(cat SKIP_CI.txt)
          if [[ "${SKIP_CI}" == true ]];then
            git push -f -o ci.variable="SKIP_CI=true" ci
          else
            git push -f ci
          fi
